# Generated by Django 5.1.2 on 2024-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='added_at',
            field=models.DateField(auto_now=True),
        ),
    ]
