# Generated by Django 5.1.2 on 2024-11-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('store', '0004_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSocialLoginView',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
            ],
            bases=('socialaccount.socialaccount',),
        ),
    ]
