# Generated by Django 5.1.2 on 2024-11-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customsocialloginview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSocialLoginView',
        ),
    ]
