"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from env.SecretKeys import AppSecretKey
from .allauth_settings import (ALLAUTH_TEMPLATES,
                              ALLAUTH_AUTHENTICATION_BACKENDS,
                              ALLUTH_INSTALLED_APPS,
                              ALLAUTH_MIDDLEWARE,
                              ALLAUTH_PROVIDERS)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = AppSecretKey.APP_MAIN_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


#- ALLAUT SETTINGS -#
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
AUTHENTICATION_BACKENDS = ALLAUTH_AUTHENTICATION_BACKENDS
SOCIALACCOUNT_PROVIDERS = ALLAUTH_PROVIDERS
SOCIALACCOUNT_LOGIN_ON_GET = True
#- redirect to social login temp to check if user in black list -#
'''
there is no tmplate just
we toke url name because the function work with redirect
'''
#> redirect allauth login and signup pages to my custom links for check if email exists or forbidden <#
LOGIN_REDIRECT_URL = 'sociallogin_page'
ACCOUNT_SIGNUP_URL = 'socialsignup_page'
#> to make email saving required <#
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "mandatory" #- optinal verification -#


INSTALLED_APPS = [
    #- store app -#.
    'store.apps.StoreConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + ALLUTH_INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
] + ALLAUTH_MIDDLEWARE

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ] + ALLAUTH_TEMPLATES,
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#- static files -#
STATIC_URL = '/static/'
# Directory where static files will be collected to (used with 'collectstatic' command)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Additional directories to look for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'raw_static'),
]


#- media -#
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
   

#- send gmail message -#
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = AppSecretKey.APP_GMAIL
EMAIL_HOST_PASSWORD = AppSecretKey.APP_GMAIL_PASSWORD
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


#- recaptcha -#
GOOGLE_RECAPTCHA_SECRET_KEY = AppSecretKey.RECAPTCHA_SECRET_KEY


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
